export enum Color {
    RED = 0xff0000,
    GREEN = 0x00ff00,
    BLUE = 0x0000ff,
    YELLOW = 0xffff00,
    CYAN = 0x00ffff,
    MAGENTA = 0xff00ff,
    WHITE = 0xffffff,
    BLACK = 0x000000,
    ORANGE = 0xffa500,
    LIME = 0x32cd32,
    PURPLE = 0x800080,
    PINK = 0xff69b4,
    TEAL = 0x008080,
    LAVENDER = 0xe6e6fa,
    OLIVE = 0x808000,
    CORAL = 0xff7f50,
    INDIGO = 0x4b0082,
    MAROON = 0x800000,
    TURQUOISE = 0x40e0d0,
    GOLD = 0xffd700,
    SILVER = 0xc0c0c0,
    GRAY = 0x808080,
    VERY_LIGHT_GREY = 0xcccccc,
    DARK_GREY = 0xaaaaaa,
    DARK_GREEN = 0x006400,
    SKY_BLUE = 0x87ceeb,
    VIOLET = 0xee82ee,
}

export const LIGHT_COLORS = [
    Color.RED,
    Color.GREEN,
    Color.YELLOW,
    Color.CYAN,
    Color.MAGENTA,
    Color.ORANGE,
    Color.LIME,
    Color.PINK,
    Color.LAVENDER,
    Color.CORAL,
    Color.TURQUOISE,
    Color.GOLD,
    Color.SILVER,
    Color.SKY_BLUE,
    Color.VIOLET,
    Color.VERY_LIGHT_GREY,
];

export const DARK_COLORS = [
    Color.BLACK,
    Color.BLUE,
    Color.MAGENTA,
    Color.PURPLE,
    Color.TEAL,
    Color.OLIVE,
    Color.INDIGO,
    Color.MAROON,
    Color.GRAY,
    Color.DARK_GREEN,
    Color.DARK_GREY,
];
export const CELLID_TO_COLORS: { [id: number]: Color } = {
    0: Color.BLACK,
    1: Color.BLUE,
    2: Color.CYAN,
    3: Color.GREEN,
    4: Color.MAGENTA,
    5: Color.RED,
    6: Color.YELLOW,
    7: Color.WHITE,
    8: Color.ORANGE,
    9: Color.PURPLE,
    10: Color.PINK,
    11: Color.LIME,
    12: Color.OLIVE,
    13: Color.TEAL,
    14: Color.DARK_GREEN,
    15: Color.TURQUOISE,
    16: Color.GOLD,
    17: Color.SILVER,
    18: Color.CORAL,
    19: Color.INDIGO,
    20: Color.MAROON,
    21: Color.VIOLET,
    22: Color.LAVENDER,
    23: Color.SKY_BLUE,
    24: Color.GRAY,
};

export type CellIdToColors = typeof CELLID_TO_COLORS;
